import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";
import localFont from "next/font/local";
import "./globals.css";
import styles from "./layout.module.css";
const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const roboto = Roboto({
  subsets: ["latin"],
  variable: "--font-roboto",
  weight: ["100", "400", "900"],
});

export const metadata: Metadata = {
  title: "Acelys NextJS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${roboto.variable}`}>
        <header className={styles.header}>
          <h1>Acelys NextJS</h1>
        </header>
        <div className={styles.container}>
          <aside className={styles.sidebar}></aside>
          {children}
        </div>
      </body>
    </html>
  );
}
